project_id = "fgquwzzyudgcmfbuvmch"

[functions.hash-pin]
verify_jwt = false

[functions.invite-member]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.yoco-webhook]
verify_jwt = false
