-- Update seeded pos_users with PBKDF2 hashes generated by the hash-pin Edge Function
-- Admin PIN: 1968, Robert PIN: 2505
UPDATE pos_users SET pin_hash = '63f8bcd1422fb90e389aebdd18f5078a:a373e03fd8d96fda2b1a9da3d13ca9d71db2ad202a432ccfef3c440cbc97438e' WHERE name = 'Admin' AND venue_id = 'eb1864cd-c9b3-4206-898d-d5300de149a5';
UPDATE pos_users SET pin_hash = 'b49126d4eca6837575a0fdd043fdb80b:a98489d05714f97054018b402f23bf5df72e3c8af1d6ece353b29e1421aa3785' WHERE name = 'Robert' AND venue_id = 'eb1864cd-c9b3-4206-898d-d5300de149a5';